### ISSUE TITLE
Revisit screenreader behavior for locale picker

### ISSUE THREAD

**Issue by camillevilla** [projectblacklight/blacklight-locale_picker#7]
This was initially implemented as `<span class="sr-only"><%= t('blacklight.toolbar.language_switch') %></span>`, but we don't have translations for this yet. 

What's the target string for this menu, @ggeisler @jvine ? "Change language"? "Language" might be slightly easier to source translations for because it doesn't have a verb.

Should this be an `aria-label` on the `ul` instead? An example is language picker on [if-me.org](https://www.if-me.org/)

**Comment by jvine** [comment]
I like the if.me.org model - it's nice and clean. No visible label; aria-label in the current language; no sr-only needed. Label = `Language` w no verb.
